HomeWork/Models/Abstract/IPhone.cs
namespace HomeWork.Models.Abstract;

public interface IPhone
{
    
}

HomeWork/Models/CreateOrder.cs
using HomeWork.Controllers;

namespace HomeWork.Models;

public class CreateOrder
{
    public Order Order { get; set; }
    public ErrorViewModel ErrorViewModel { get; set; }

    public CreateOrder()
    {
        ErrorViewModel = new ErrorViewModel();
        Order = new Order();
    }
}

HomeWork/Models/CreatePhone.cs
namespace HomeWork.Models;

public class CreatePhone
{
    public Phone Phone { get; set; }
    public ErrorViewModel ErrorViewModel { get; set; }

    public CreatePhone()
    {
        ErrorViewModel = new ErrorViewModel();
    }
}

HomeWork/Models/ErrorViewModel.cs
using FluentValidation.Results;

namespace HomeWork.Models;

public class ErrorViewModel
{
    public List<ValidationFailure> Errors { get; set; }

    public ErrorViewModel()
    {
        Errors = new List<ValidationFailure>();
    }
    
}

HomeWork/Models/Order.cs
namespace HomeWork.Models;

public class Order
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string PhoneNumber { get; set; }

    public int PhoneId { get; set; }
    public Phone Phone { get; set; }
}

HomeWork/Models/Phone.cs
namespace HomeWork.Models;

public class Phone
{
    public int Id { get; set; }
    public string Manufacture { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public double Coast { get; set; }
}

HomeWork/Models/PhoneContext.cs
using HomeWork.Models;
using Microsoft.EntityFrameworkCore;

namespace HomeWork.Service;

public class PhoneContext : DbContext
{
    public DbSet<Phone> Phone { get; set; }
    public DbSet<Order> Order { get; set; }

    public PhoneContext(DbContextOptions<PhoneContext> options) : base(options){}
}

HomeWork/Controllers/FileController.cs
using HomeWork.Models;
using HomeWork.Service.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace HomeWork.Controllers;

public class FileController : Controller
{
    private readonly IDownloadFileService _downloadFileService;

    public FileController(IDownloadFileService downloadFileService)
    {
        _downloadFileService = downloadFileService;
    }
    
    public IActionResult GetFile(int id)
    {
        var file = _downloadFileService.Download(id);

        if (string.IsNullOrEmpty(file.FileName))
            return NotFound();
        
        return PhysicalFile(file.FilePath, file.FileType, file.FileName);
    }
}

HomeWork/Controllers/OrderController.cs
using FluentValidation.Results;
using HomeWork.Models;
using HomeWork.Service.Abstract;
using HomeWork.Validation;
using Microsoft.AspNetCore.Mvc;

namespace HomeWork.Controllers;

public class OrderController : Controller
{
    private readonly IOrderService _orderService;
    private readonly CreateOrderValidation _createOrderValidation;
    private readonly CreateOrder _createOrder;

    public OrderController(IOrderService orderService, CreateOrderValidation createOrderValidation, CreateOrder createOrder)
    {
        _orderService = orderService;
        _createOrderValidation = createOrderValidation;
        _createOrder = createOrder;
    }
    [HttpGet]
    public IActionResult Create(int id)
    {
        var phone = _orderService.GetPhoneById(id);

        if (string.IsNullOrEmpty(phone.Title))
            return NotFound();
        _createOrder.Order.Phone = phone;
        
        return View(_createOrder);
    }
    
    [HttpPost]
    public IActionResult Create(CreateOrder createOrder)
    {
        ValidationResult validate = _createOrderValidation.Validate(createOrder.Order);
        if (validate.IsValid)
        {
            _orderService.Add(createOrder.Order);
            return RedirectToAction("Orders");
        }
        
        createOrder.ErrorViewModel.Errors = validate.Errors;
        var phone = _orderService.GetPhoneById(createOrder.Order.PhoneId);
        createOrder.Order.Phone = phone;
        return View(createOrder);
    }

    public IActionResult Orders()
    {
        var orders = _orderService.GetAll();
        return View(orders);
    }
}

HomeWork/Controllers/PhoneController.cs
using FluentValidation.Results;
using HomeWork.Models;
using HomeWork.Service;
using HomeWork.Service.Abstract;
using HomeWork.Validation;
using Microsoft.AspNetCore.Mvc;

namespace HomeWork.Controllers;

public class PhoneController : Controller
{
    private readonly IPhoneService _phoneService;
    private readonly CreatePhoneValidator _createPhoneValidator;
    private readonly CreatePhone _createPhone;
    
    
    public PhoneController(IPhoneService phoneService, CreatePhoneValidator createPhoneValidator, CreatePhone createPhone)
    {
        _phoneService = phoneService;
        _createPhoneValidator = createPhoneValidator;
        _createPhone = createPhone;
    }

    [HttpGet]
    public IActionResult Index()
    {
        List<Phone> phones = _phoneService.GetAll();
        return View(phones);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View(_createPhone);
    }

    [HttpPost]
    public IActionResult Create(Phone phone)
    {
        ValidationResult validator = _createPhoneValidator.Validate(phone);

        if (validator.IsValid)
            _phoneService.Add(phone);
        else
        {
            _createPhone.ErrorViewModel.Errors = validator.Errors;
            return View(_createPhone);
        }

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult About(int id)
    {
       Phone phone = _phoneService.GetById(id);
       return View(phone);
    }
    
    [HttpGet]
    public IActionResult OfficialSite(string manufacture)
    {
        return Redirect($@"https:\\{manufacture}.com");
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        Phone phone = _phoneService.GetById(id);
        _createPhone.Phone = phone;
        return View(_createPhone);
    }
    
    [HttpPost]
    public IActionResult Edit(Phone phone)
    {
        ValidationResult validator = _createPhoneValidator.Validate(phone);

        if (validator.IsValid)
            _phoneService.EditPhone(phone);
        else
        {
            _createPhone.ErrorViewModel.Errors = validator.Errors;
            _createPhone.Phone = phone;
            return View(_createPhone);
        }
        return RedirectToAction("Index");
    }
}

HomeWork/Views/Order/Create.cshtml
@model CreateOrder

@{
    ViewBag.Title = "Создать заказ";
    Layout = "_Layout";
}

<h2>Заказ</h2>

<div class="row">
<div class="col-md-6">
    <form asp-action="Create" asp-controller="Order" method="post">
        <div class="form-group mb-3">
            <label for="Name" class="mb-2">Имя покупателя</label>
            <input asp-for="Order.Name"
                   type="text"
                   class="form-control"
                   id="Name"
                   placeholder="Имя">
        </div>
        <div class="form-group mb-3">
            <label for="phone" class="mb-2">Номер телефона</label>
            <input asp-for="Order.PhoneNumber"
                   type="text"
                   class="form-control"
                   id="phone"
                   placeholder="+ 7 777 777 77 77">
        </div>
        <div class="form-group mb-3">
            <label for="device" class="mb-2">Выбран телефон</label>
            <input disabled type="text"
                   class="form-control"
                   id="device"
                   value="@Model.Order.Phone.Title">
        </div>
        <input type="hidden" asp-for="Order.PhoneId" value="@Model.Order.Phone.Id">
        <button type="submit" class="btn btn-outline-info mt-3">Заказать</button>
    </form>
    @{
            if (Model.ErrorViewModel.Errors.Any())
               {
                   foreach (var error in Model.ErrorViewModel.Errors)
                   {
                        <p class="p-3 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3">
                            @error.ErrorMessage
                        </p>
                   }
               }
        }
</div>
</div>

HomeWork/Views/Order/Orders.cshtml
@model List<Order>

@{
    ViewBag.Title = "Заказы";
    Layout = "_Layout";
}

<div class="text-center">
    <h2>Список заказов</h2>
</div>
<div class="table_section">
    @{
        if (!Model.Any())
        {
            <h2>Список заказов пуст</h2>
        }
        else
        {
            <table class="table" style="width: 100%;">
                <tr>
                    <th>#Id</th>
                    <th>Имя покупателя</th>
                    <th>Номер телефона</th>
                    <th>Наименование устройства</th>
                    <th>Сумма</th>
                </tr>
                @foreach (var order in Model)
                {
                    <tr>
                        <td>@order.Id</td>
                        <td>@order.Name</td>
                        <td>@order.PhoneNumber</td>
                        <td>@order.Phone.Manufacture @order.Phone.Title</td>
                        <td>@order.Phone.Coast</td>
                    </tr>
                }
            </table>
        }
    }
</div>

HomeWork/Views/Phone/About.cshtml
@model Phone

@{
    ViewBag.Title = "О товаре";
    Layout = "_Layout";
}

<div class="row justify-content-center">
    <h2>Все что Вы хотели знать о @Model.Title</h2>
    <div class="card px-0" style="width: 100%;">
        <div class="card-body">
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">@Model.Description</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Производитель: @Model.Manufacture</li>
            <li class="list-group-item">Стоимость: @Model.Coast</li>
        </ul>
        <div class="card-body">
            <a asp-route-id="@Model.Id" asp-controller="Order" asp-action="Create" class="my-3 btn btn-success">Сделать заказ</a>
            <a asp-route-id="@Model.Id" 
               asp-controller="File" 
               asp-action="GetFile" class="my-3 btn btn-dark">Скачать тех. спецификации</a>
            <a asp-route-manufacture="@Model.Manufacture" asp-controller="Phone" asp-action="OfficialSite" class="my-3 btn btn-info">На сайт производителя</a>
        </div>
    </div>
</div>

HomeWork/Views/Phone/Create.cshtml
@model CreatePhone

@{
    ViewBag.Title = "Создание товара";
    Layout = "_Layout";
}

    <h2>Запоните поля для добавления нового телефона</h2>
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">
            <div class="form-group mb-3">
                <label for="manufacture" class="mb-2">Производитель</label>
                <input asp-for="Phone.Manufacture"
                       type="text"
                       class="form-control"
                       id="manufacture"
                       placeholder="Apple">
            </div>
            <div class="form-group mb-3">
                <label for="title" class="mb-2">Модель</label>
                <input asp-for="Phone.Title"
                       type="text"
                       class="form-control"
                       id="title"
                       placeholder="IPhone 13 Pro Max">
            </div>
            <div class="form-group mb-3">
                <label for="weight" class="mb-2">Описание</label>
                <textarea  asp-for="Phone.Description"
                       type="text"
                       class="form-control"
                       id="weight"
                       placeholder="ну конечно не 'топ за свои деньги' как сясёми, за то нет рекламы в проводнике...">
                </textarea>
            </div>
            <div class="form-group mb-3">
                <label for="price" class="mb-2">Цена</label>
                <input asp-for="Phone.Coast"
                       type="text"
                       class="form-control"
                       id="price"
                       placeholder="10000000000000$">
            </div>
            <button type="submit" class="btn btn-outline-info mt-3">Создать</button>
        </form>
    </div>
    <div class="mt-5">
    @{
        if (Model.ErrorViewModel.Errors.Any())
           {
               foreach (var error in Model.ErrorViewModel.Errors)
               {
                    <p class="p-3 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3">
                        @error.ErrorMessage
                    </p>
               }
           }
    }
    </div>
</div>

HomeWork/Views/Phone/Edit.cshtml
@model CreatePhone

@{
    ViewBag.Title = "Изменение товара";
    Layout = "_Layout";
}

<h2>Отредактируйте поля для изменения товара</h2>
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" method="post">
            <div class="form-group mb-3">
                <label for="manufacture" class="mb-2">Производитель</label>
                <input asp-for="Phone.Manufacture"
                       type="text"
                       class="form-control"
                       id="manufacture"
                       placeholder="Apple"
                       value="@Model.Phone.Manufacture">
            </div>
            <div class="form-group mb-3">
                <label for="title" class="mb-2">Модель</label>
                <input asp-for="Phone.Title"
                       type="text"
                       class="form-control"
                       id="title"
                       placeholder="IPhone 13 Pro Max"
                       value="@Model.Phone.Title">
            </div>
            <div class="form-group mb-3">
                <label for="weight" class="mb-2">Описание</label>
                <textarea  asp-for="Phone.Description"
                       type="text"
                       class="form-control"
                       id="weight"
                        value="@Model.Phone.Description"
                       placeholder="ну конечно не 'топ за свои деньги' как сясёми, за то нет рекламы в проводнике...">
                </textarea>
            </div>
            <div class="form-group mb-3">
                <label for="price" class="mb-2">Цена</label>
                <input asp-for="Phone.Coast"
                       type="text"
                       class="form-control"
                       id="price"
                       value="@Model.Phone.Coast"
                       placeholder="10000000000000$">
            </div>
            <input type="hidden" asp-for="Phone.Id" value="@Model.Phone.Id"/>
            <button type="submit" class="btn btn-outline-info mt-3">Редактировать</button>
        </form>
    </div>
    <div class="mt-5">
    @{
        if (Model.ErrorViewModel.Errors.Any())
           {
               foreach (var error in Model.ErrorViewModel.Errors)
               {
                    <p class="p-3 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3">
                        @error.ErrorMessage
                    </p>
               }
           }
    }
    </div>
</div>

HomeWork/Views/Phone/Index.cshtml
@model List<Phone>

@{
    ViewBag.Title = "Главная";
    Layout = "_Layout";
}

<div class="text-center">
    <h2>Список телефонов</h2>
</div>
<a asp-action="Create" class="my-3 btn btn-outline-info">Добавить телефон</a>
<div class="table_section">
    @{
        if (!Model.Any())
        {
            <h2>Список телефонов пуст</h2>
        }
        else
        {
            <table class="table" style="width: 100%;">
                <tr>
                    <th>#Id</th>
                    <th>Производитель</th>
                    <th>Модель</th>
                    <th>Цена</th>
                    <th>Действие</th>
                </tr>
                @foreach (var phone in Model)
                {
                    <tr>
                        <td>@phone.Id</td>
                        <td>@phone.Manufacture</td>
                        <td>@phone.Title</td>
                        <td>@phone.Coast</td>
                        <td>
                            <a asp-controller="Phone"
                               asp-action="About"
                               asp-route-id="@phone.Id" class="my-3 btn btn-outline-info d-inline">Подробнее</a>
                            <a asp-controller="Order"
                               asp-action="Create"
                               asp-route-id="@phone.Id" class="my-3 btn btn-success d-inline">Заказать</a>
                            <a asp-controller=""
                               asp-action="Edit"
                               asp-route-id="@phone.Id" class="my-3 btn btn-danger d-inline">Изменить</a>
                        </td>
                    </tr>
                }
            </table>
        }
    }
</div>

HomeWork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - HomeWork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Phone" asp-action="Index">Список устройств</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Orders">Список заказов</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Phone" asp-action="Create">Добавить телефон</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - HomeWork - <a asp-area="" asp-controller="" asp-action="">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>